function [ KL_value_vector01,KLP_value_corr_vector01,KLP_value_non_corr_vector01,KLProb_corr_vector01,KLProb_non_corr_vector01,...
                NT_value_vector01,TP_value_vector01,TP_value_non_corr_vector01,TProb_corr_vector01,TProb_non_corr_vector01,...
                LE_value_vector01,LEP_value_corr_vector01,LEP_value_non_corr_vector01,LEProb_corr_vector01,LEProb_non_corr_vector01,...
                LE_KL_T_P_value_corr_vector01,LE_KL_P_value_corr_vector01,...
                LE_T_P_value_corr_vector01,KL_T_P_value_corr_vector01...
                LE_KL_T_P_value_non_corr_vector01,LE_KL_P_value_non_corr_vector01...
                LE_T_P_value_non_corr_vector01,KL_T_P_value_non_corr_vector01]=Total_LEKLT_calculation(peptideseqence,Interval_data_A,TimeInterval_A,...
                    Orbit_Pep_N_time,TOF_retentiont01l1,isoList,Pep_labeling_eff,...
                    KL_pdf_pp_corr01,KL_pdf_pp_non_corr01,KL_cdf_pp_corr01,KL_cdf_pp_non_corr01,...
                    PP_null01,T_mu_corr01,T_sigma_corr01,T_mu_non_corr01,T_sigma_non_corr01,...
                    LE_pdf_pp_corr01,LE_pdf_pp_non_corr01,LE_cdf_pp_corr01,LE_cdf_pp_non_corr01,...
                    LEKLT_pdf_pp_corr01,LEKL_pdf_pp_corr01,LET_pdf_pp_corr01,KLT_pdf_pp_corr01,...
                    LEKLT_cdf_pp_corr01,LEKL_cdf_pp_corr01,LET_cdf_pp_corr01,KLT_cdf_pp_corr01,...
                    LEKLT_pdf_pp_non_corr01,LEKL_pdf_pp_non_corr01,LET_pdf_pp_non_corr01,KLT_pdf_pp_non_corr01,...
                    LEKLT_cdf_pp_non_corr01,LEKL_cdf_pp_non_corr01,LET_cdf_pp_non_corr01,KLT_cdf_pp_non_corr01)
        %%%%%%%%%%% KL value Pvalue and probility 
        [KL_value_vector01,KLP_value_corr_vector01,KLP_value_non_corr_vector01,...
            KLProb_corr_vector01,KLProb_non_corr_vector01]=Calculate_PV_KLnulldistribution(peptideseqence,Interval_data_A,...
            KL_pdf_pp_corr01,KL_pdf_pp_non_corr01,KL_cdf_pp_corr01,KL_cdf_pp_non_corr01);
        %%%%%%%%%%%
        %%%%%%%%%%% T value Pvalue and probility
        [NT_value_vector01,TP_value_vector01,TP_value_non_corr_vector01,...
            TProb_corr_vector01,TProb_non_corr_vector01]=Calculate_PV_Tnulldistribution(TimeInterval_A,Interval_data_A,...
            TOF_retentiont01l1,Orbit_Pep_N_time,...
            PP_null01,T_mu_corr01,T_sigma_corr01,T_mu_non_corr01,T_sigma_non_corr01);
        %%%%%%%%%%%
        %%%%%%%%%%% LE value Pvalue and probility
        [LE_value_vector01,LEP_value_corr_vector01,LEP_value_non_corr_vector01,...
            LEProb_corr_vector01,LEProb_non_corr_vector01]=Calculate_PV_LEnulldistribution(Interval_data_A,...
            isoList,Pep_labeling_eff,...
            LE_pdf_pp_corr01,LE_pdf_pp_non_corr01,LE_cdf_pp_corr01,LE_cdf_pp_non_corr01);
        %%%%%%%%%%%
        LE_KL_T_P_value_corr_vector01=ppval(LEKLT_cdf_pp_corr01,log(TProb_corr_vector01.*LEProb_corr_vector01.*KLProb_corr_vector01));
        LE_KL_P_value_corr_vector01=ppval(LEKL_cdf_pp_corr01,log(LEProb_corr_vector01.*KLProb_corr_vector01));
        LE_T_P_value_corr_vector01=ppval(LET_cdf_pp_corr01,log(LEProb_corr_vector01.*TProb_corr_vector01));
        KL_T_P_value_corr_vector01=ppval(KLT_cdf_pp_corr01,log(KLProb_corr_vector01.*TProb_corr_vector01));
        LE_KL_T_P_value_non_corr_vector01=1-ppval(LEKLT_cdf_pp_non_corr01,log(TProb_non_corr_vector01.*LEProb_non_corr_vector01.*KLProb_non_corr_vector01));
        LE_KL_P_value_non_corr_vector01=1-ppval(LEKL_cdf_pp_non_corr01,log(LEProb_non_corr_vector01.*KLProb_non_corr_vector01));
        LE_T_P_value_non_corr_vector01=1-ppval(LET_cdf_pp_non_corr01,log(LEProb_non_corr_vector01.*TProb_non_corr_vector01));
        KL_T_P_value_non_corr_vector01=1-ppval(KLT_cdf_pp_non_corr01,log(KLProb_non_corr_vector01.*TProb_non_corr_vector01));

        
        
        
        
        
        
        
        
        
        
        
        
        